# This file was generated by GoReleaser. DO NOT EDIT.
class Tfr < Formula
  desc "A lightweight commandline TFRecords processor"
  homepage "https://github.com/emla2805/tfr"
  version "0.1-beta.2"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/emla2805/tfr/releases/download/v0.1-beta.2/tfr_0.1-beta.2_darwin_amd64.tar.gz"
    sha256 "3cb0d47e2e1fe1ace30d6b70a19d4404c411da0affe57b4d8b823d2029be9a1b"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/emla2805/tfr/releases/download/v0.1-beta.2/tfr_0.1-beta.2_linux_amd64.tar.gz"
    sha256 "9c043081804be692f497b6e7a1c3283ab45b2d048cce399a62db0e970f403727"
  end

  def install
    bin.install "tfr"
  end
end
