# This file was generated by GoReleaser. DO NOT EDIT.
class Tfr < Formula
  desc "A lightweight commandline TFRecords processor"
  homepage "https://github.com/emla2805/tfr"
  version "0.1-beta.4"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/emla2805/tfr/releases/download/v0.1-beta.4/tfr_0.1-beta.4_darwin_amd64.tar.gz"
    sha256 "52e3ee1c9305c0769429d1caf784de513d0d3ab58d8ec448d02031f560d39a1a"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/emla2805/tfr/releases/download/v0.1-beta.4/tfr_0.1-beta.4_linux_amd64.tar.gz"
    sha256 "fd9118398a2ec825676e156cde731f303b8f1cba537b6405cbddb2ec324484a0"
  end

  def install
    bin.install "tfr"
  end
end
