# This file was generated by GoReleaser. DO NOT EDIT.
class Tfr < Formula
  desc "A lightweight commandline TFRecords processor"
  homepage "https://github.com/emla2805/tfr"
  version "0.1-beta.3"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/emla2805/tfr/releases/download/v0.1-beta.3/tfr_0.1-beta.3_darwin_amd64.tar.gz"
    sha256 "6535f95907af3dd7d6d86bc20d384fbd62076b24ff0e0c7bcacdf9bfb2641449"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/emla2805/tfr/releases/download/v0.1-beta.3/tfr_0.1-beta.3_linux_amd64.tar.gz"
    sha256 "e8ba9c2720a785943c118d8324577708aec18d64c5a0c211d3a9ef2d3d2c1a15"
  end

  def install
    bin.install "tfr"
  end
end
