# This file was generated by GoReleaser. DO NOT EDIT.
class Tfr < Formula
  desc "A lightweight commandline TFRecords processor"
  homepage "https://github.com/emla2805/tfr"
  version "0.1.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/emla2805/tfr/releases/download/v0.1.0/tfr_0.1.0_darwin_amd64.tar.gz"
    sha256 "9d9f30f787ea720fa27f6135f8202c8225c3d3cf0475125ca826d9df13548b72"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/emla2805/tfr/releases/download/v0.1.0/tfr_0.1.0_linux_amd64.tar.gz"
    sha256 "7e34b1e5430f674cc0dec5e4c5c9dde8fa456728602b94f4919a39bbc86316c7"
  end

  def install
    bin.install "tfr"
  end
end
